meta_product_name: "VUE Gallerie"
meta_title: "VUE Gallerie - Give wings to your creativity!"
meta_description: "Be independent, curate your own shows and exhibit your art. "
meta_image: "favicon-art.svg" # should exist in `app/assets/images/`
